### ISSUE TITLE
API changes broke the client

### ISSUE THREAD

**Issue by abartov** [klacointe/wikidata-client#19]
Some Wikidata API changes have made the current version broken by default, with tests failing:
1. HTTPS now required.
2. query-continue no longer supported (for search results)
3. hard-coded results in the spec files (down to the precise number of expected hits for "Michael Jackson"...) have come to no longer be accurate.

I have submitted a pull request that fixes all of these issues and bumps the version, with separate commits.

**Comment by klacointe** [comment]
Fix https://github.com/klacointe/wikidata-client/commit/6e0083f60cc0c79e51da2c4f7dcd791e4cff8a22
