### ISSUE TITLE
Hashie warnings

### ISSUE THREAD

**Issue by pmackay** [klacointe/wikidata-client#26]
When I use this gem to get the title of an item from its ID, this warning is output many times to the console:
`WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#hash defined in Hash. This can cause unexpected behavior when accessing the key as a property. You can still access the key via the #[] method.`

I believe the latest version of hashie has ability to disable these warnings if they can be ignored.

**Comment by SprouterB** [comment]
Any way to solve this?

**Comment by klacointe** [comment]
Can you try https://rubygems.org/gems/wikidata-client/versions/0.1.0.pre.rc1

**Comment by tamaloa** [comment]
> Can you try https://rubygems.org/gems/wikidata-client/versions/0.1.0.pre.rc1

Worked for me. No more hashie warnings

```
ruby -v
ruby 3.2.2 
rails --version
Rails 7.1.0.rc1
```

**Comment by tamaloa** [comment]
If possible, maybe you could release a new gem version?
The last stable version on rubygems is [0.0.12](https://rubygems.org/gems/wikidata-client/versions/0.0.12) from December 13, 2017

Thanks for your work :+1:

**Comment by klacointe** [comment]
done https://rubygems.org/gems/wikidata-client
